FIRST_NAMES = [
    "Alex",
    "Jordan",
    "Taylor",
    "Morgan",
    "Casey",
    "Riley",
    "Avery",
    "Quinn",
    "Cameron",
    "Skyler",
    "Dakota",
    "Reese",
    "Rowan",
    "Parker",
    "Jamie",
    "Drew",
    "Emerson",
    "Blake",
    "Hayden",
    "Logan",
    "Sawyer",
    "Finley",
    "Arden",
    "Kai",
    "Jules",
    "Remy",
    "Elliot",
    "Harper",
    "Sage",
    "Kendall",
    "Ariel",
    "Robin",
    "Charlie",
    "Toby",
    "Luca",
    "Noel",
    "Shiloh",
    "Micah",
    "Alden",
    "Briar",
    "Callum",
    "Darian",
    "Evan",
    "Felix",
    "Galen",
    "Isaac",
    "Jonah",
    "Leo",
    "Mason",
    "Nolan",
]

LAST_NAMES = [
    "Hart",
    "Cole",
    "Bennett",
    "Shaw",
    "Griffin",
    "Pryce",
    "Delaney",
    "Sutton",
    "Monroe",
    "Keller",
    "Hollis",
    "Bishop",
    "Carver",
    "Lang",
    "Donovan",
    "Mercer",
    "Ellis",
    "Vaughn",
    "Sinclair",
    "Adler",
    "Barrett",
    "Caldwell",
    "Dalton",
    "Easton",
    "Fletcher",
    "Garrett",
    "Hendrix",
    "Irving",
    "Jennings",
    "Keaton",
    "Lawson",
    "Maddox",
    "Nash",
    "Oakley",
    "Prescott",
    "Quincy",
    "Ramsey",
    "Shepard",
    "Thatcher",
    "Underwood",
    "Vance",
    "Whitaker",
    "York",
    "Zimmer",
    "Bradford",
    "Chandler",
    "Dawson",
    "Emery",
    "Foster",
    "Garrison",
]

IDENTIFIERS = [
    "Shadow", "Rise", "Fall", "Return", "Curse", "Legend", "Secret", "Wrath", "Revenge", "Call",
    "Edge", "Echo", "Whisper", "Storm", "Fire", "Ice", "Blood", "Crown", "Blade", "Song",
    "Dance", "Dream", "Light", "Darkness", "Path", "Gate", "Last", "First", "Final", "Hidden",
    "Lost", "Broken", "Burning", "Silent", "Golden", "Crimson", "Iron", "Forgotten", "Eternal", "Ancient",
    "Midnight", "Lonely", "Sacred", "Wild", "Fading", "Shattered", "Frozen", "Endless", "Haunting", "Secret"
]

OBJECTS = [
    "Empire", "Kingdom", "Dragon", "Phoenix", "Titans", "Warriors", "Shadows", "Stars", "Moon", "Sun",
    "Forest", "Sea", "Mountain", "Desert", "City", "Crown", "Throne", "Sword", "Treasure", "Temple",
    "Prophecy", "Guardian", "Hunter", "Outlaw", "Knight", "Queen", "King", "Prince", "Princess", "Beast",
    "Monster", "Ghost", "Spirit", "Legend", "Voyage", "Journey", "Storm", "Battle", "War", "Frontier",
    "Labyrinth", "Galaxy", "Island", "Castle", "Empire", "Rebellion", "Fortress", "Oracle", "River", "Horizon"
]