services:
  ui:
    build: ./bacon_frontend
    ports:
      - 8501:8501
    links:
      - "server"
  server:
    build: ./bacon_backend
    ports:
      - 5000:5000
  queue:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass
  consumer:
    build: ./bacon_consumer