FROM python:3.12-slim

RUN mkdir /usr/bacon_frontend/

WORKDIR /usr/bacon_frontend/

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY bacon_frontend/ ./bacon_frontend/
RUN chmod 777 -R bacon_frontend

CMD ["streamlit", "run", "--server.address", "0.0.0.0", "/usr/bacon_frontend/bacon_frontend/UI.py"]