FROM python:3.12-slim

RUN mkdir /usr/bacon_backend/

WORKDIR /usr/bacon_backend/

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY setup.py ./
COPY bacon_backend/ ./bacon_backend/


RUN pip install .
RUN chmod 777 -R bacon_backend
# RUN python bacon_backend/generate_db.py

ENV FLASK_APP /usr/bacon_backend/bacon_backend/app.py

CMD ["sh", "-c", "python bacon_backend/generate_db.py ; flask run --host 0.0.0.0"]